id_need_build = "need_build"  # If false project create, but not building
id_create_app = "create_app"
id_need_clear = "need_clear"  # If false project not delete after script executed
id_version_name = "version_name"
id_version_code = "version_code"
id_def_bundle = "default_bundle"  # Default Bundle from master android project
branch = "branch"  # Default Bundle from master android project
id_email = "email"
ios_company_name = "ios_company_name"
id_build_email = "id_build_email"
id_company_id = "id_company_id"
